name = "Kolja Lubitz"
description = "Pythonic web developer by day. Indie Game Developer at night 🎮"
keywords = "Kolja Lubitz, python, django, ALPACA, game engine, point and click"
image = "kolja.jpeg"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
base_url = "https://pinguin999.github.io/"

[[sections]]
title = "Game Dev"
description = "Here are my game dev projects"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Portal Dogs"
description = "As king of the dogs your mission is to find all your loyal subjects and guide them to the portal."
url = "https://portaldogs.com/"
[[sections.items]]
title = "ALPACA Engine"
description = "A Library for Point And Click Adventures"
url = "https://alpaca-engine.de/"
# [[sections.items]]
# title = "Prisoners"
# description = "A gripping thriller entangling a detective in a web of secrets during a kidnapping investigation"
# url = "https://www.imdb.com/title/tt1392214/"

[[sections]]
title = "Links"
description = "Find me on the web"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "X"
url = "https://x.com/Pinguin666"
[[sections.items]]
title = "Mastodon"
url = "https://mastodon.gamedev.place/@pinguin"
[[sections.items]]
title = "LinkedIn"
url = "https://www.linkedin.com/in/kolja-lubitz-10b9112a/"
# [[sections.items]]
# title = "Rotten Tomatoes"
# url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
